// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

// Package precommit installs and runs the git pre-commit hook.
package precommit

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

const marker = "# nimblegate-managed pre-commit hook"

const hookTemplate = `#!/usr/bin/env bash
` + marker + `
# Generated by ` + "`nimblegate init`" + `. To uninstall: delete this file.

# Fail-open if nimblegate is not on PATH (don't break commits because the tool moved).
if ! command -v nimblegate >/dev/null 2>&1; then
    echo "warning: nimblegate not on PATH; skipping pre-commit checks" >&2
    exit 0
fi

exec nimblegate check --trigger=pre-commit
`

// Install writes .git/hooks/pre-commit. Errors if the .git directory does not
// exist, or if an existing pre-commit hook is not nimblegate-managed.
func Install(repoRoot string) error {
	gitHooks := filepath.Join(repoRoot, ".git", "hooks")
	if _, err := os.Stat(gitHooks); errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("precommit.Install: %s does not exist; is %s a git repo?", gitHooks, repoRoot)
	} else if err != nil {
		return fmt.Errorf("precommit.Install: stat %s: %w", gitHooks, err)
	}

	hookPath := filepath.Join(gitHooks, "pre-commit")
	if existing, err := os.ReadFile(hookPath); err == nil {
		if !strings.Contains(string(existing), marker) {
			return fmt.Errorf("precommit.Install: %s exists and is not nimblegate-managed; refusing to overwrite", hookPath)
		}
	}
	if err := os.WriteFile(hookPath, []byte(hookTemplate), 0o755); err != nil {
		return fmt.Errorf("precommit.Install: write %s: %w", hookPath, err)
	}
	return nil
}
