// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

package commands

import (
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

// defaultCaddyfilePath is where Caddy looks by default on Debian/Ubuntu/Alpine.
// Overridable via --caddyfile for non-standard installs.
const defaultCaddyfilePath = "/etc/caddy/Caddyfile"

// caddyfileTemplate is the minimal Caddy config nimblegate ships. Renders
// with one placeholder: ${DOMAIN}. Reverse-proxies the dashboard at
// 127.0.0.1:7900 and applies sane security headers. Auto-HTTPS via
// Let's Encrypt is implicit - Caddy provisions the cert on startup if
// the domain resolves to this box and ports 80/443 are reachable.
const caddyfileTemplate = `# Generated by ` + "`nimblegate gateway tls-setup`" + `. Edit manually if you need to
# tweak, but ` + "`gateway tls-setup --domain <new>`" + ` will regenerate it.

${DOMAIN} {
	# Reverse-proxy to the dashboard's loopback bind. The dashboard's own
	# ` + "`gateway bind localhost`" + ` step has already flipped it off 0.0.0.0
	# before this Caddyfile lands.
	reverse_proxy 127.0.0.1:7900

	encode gzip zstd

	# Log access in JSON so structured-log tooling (vector, journalctl
	# --output=json, Promtail) can parse it without a regex.
	log {
		output file /var/log/caddy/${DOMAIN}-access.log
		format json
	}

	header {
		# 2-year HSTS: once the operator visits HTTPS, browsers refuse
		# to fall back to HTTP for this domain. Standard hardening for a
		# single-tenant admin dashboard.
		Strict-Transport-Security "max-age=63072000; includeSubDomains"
		# Defensive headers: block content-type sniffing, frame embedding,
		# and aggressive referrer leakage.
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "strict-origin-when-cross-origin"
	}
}
`

// gatewayTLSSetup wires the public-internet deployment path: install Caddy
// if missing, write a templated Caddyfile, flip the dashboard's bind to
// 127.0.0.1 via the existing gateway-bind logic, restart both services.
// One command takes the operator from a LAN install to a public HTTPS
// install without hand-editing systemd or generating certs.
func gatewayTLSSetup(args []string) int {
	return gatewayTLSSetupWith(args, os.Stdin, os.Stdout, os.Stderr, realSystemctl, realLookPath)
}

// lookPathFunc abstracts exec.LookPath so tests can simulate "caddy not
// installed" without touching the real $PATH.
type lookPathFunc func(name string) (string, error)

func realLookPath(name string) (string, error) {
	return exec.LookPath(name)
}

// gatewayTLSSetupWith is the testable entry. Same flag surface; stdin/stdout/
// stderr + systemctl + lookPath injected so the tests don't shell out, write
// to /etc/, or restart services.
func gatewayTLSSetupWith(args []string, stdin io.Reader, stdout, stderr io.Writer, systemctl systemctlRunner, lookPath lookPathFunc) int {
	flags := flag.NewFlagSet("gateway tls-setup", flag.ContinueOnError)
	flags.SetOutput(stderr)
	domain := flags.String("domain", "", "public domain name pointing at this gateway (DNS A/AAAA record required)")
	caddyfile := flags.String("caddyfile", defaultCaddyfilePath, "path to write the Caddyfile")
	unit := flags.String("unit", defaultUnitPath, "path to the dashboard systemd unit (passed through to gateway bind)")
	dryRun := flags.Bool("dry-run", false, "print actions without writing files or running systemctl")
	force := flags.Bool("force", false, "overwrite an existing Caddyfile without prompting")
	noBindFlip := flags.Bool("no-bind-flip", false, "skip the gateway bind localhost step (rare, assume operator already bound to localhost)")
	if err := flags.Parse(args); err != nil {
		return 2
	}

	if *domain == "" {
		fmt.Fprintln(stderr, "nimblegate gateway tls-setup: --domain is required")
		fmt.Fprintln(stderr, "  example: nimblegate gateway tls-setup --domain nimblegate.example.com")
		return 2
	}
	if !isPlausibleDomain(*domain) {
		fmt.Fprintf(stderr, "nimblegate gateway tls-setup: %q doesn't look like a domain (need at least one dot, alphanumeric + - + .)\n", *domain)
		return 2
	}

	// Step 1 - confirm Caddy is installed. We don't auto-install; that
	// crosses into package-management responsibility the gateway hasn't
	// taken on before. Print the apt/yum/apk command and stop if missing.
	if _, err := lookPath("caddy"); err != nil {
		fmt.Fprintln(stderr, "nimblegate gateway tls-setup: caddy not found on PATH")
		fmt.Fprintln(stderr, "  Install with one of:")
		fmt.Fprintln(stderr, "    Debian/Ubuntu: apt install -y caddy")
		fmt.Fprintln(stderr, "    Alpine:        apk add caddy")
		fmt.Fprintln(stderr, "    Other:         see https://caddyserver.com/docs/install")
		fmt.Fprintln(stderr, "  Then re-run this command.")
		return 1
	}

	// Step 2 - confirm the dashboard systemd unit exists; gateway bind
	// needs it. Catch the operator who hasn't gone through the LAN-install
	// recipe yet.
	if _, err := os.Stat(*unit); err != nil {
		fmt.Fprintf(stderr, "nimblegate gateway tls-setup: dashboard unit not found at %s\n", *unit)
		fmt.Fprintln(stderr, "  Run the LAN install steps in docs/server/SETUP-proxmox-trixie.md first.")
		return 1
	}

	// Step 3 - render the Caddyfile body.
	body := strings.ReplaceAll(caddyfileTemplate, "${DOMAIN}", *domain)

	if *dryRun {
		fmt.Fprintf(stdout, "[dry-run] would write %s (mode 0644):\n%s\n", *caddyfile, body)
		fmt.Fprintf(stdout, "[dry-run] would call gateway bind localhost (unit: %s)\n", *unit)
		fmt.Fprintln(stdout, "[dry-run] would run: systemctl daemon-reload, systemctl restart caddy, systemctl restart nimblegate-dashboard")
		return 0
	}

	// Step 4 - write the Caddyfile (refuse to overwrite without --force).
	if _, err := os.Stat(*caddyfile); err == nil && !*force {
		fmt.Fprintf(stderr, "nimblegate gateway tls-setup: %s already exists; pass --force to overwrite\n", *caddyfile)
		return 1
	}
	if err := os.MkdirAll(filepath.Dir(*caddyfile), 0o755); err != nil {
		fmt.Fprintf(stderr, "nimblegate gateway tls-setup: mkdir Caddyfile dir: %v\n", err)
		return 2
	}
	if err := os.WriteFile(*caddyfile, []byte(body), 0o644); err != nil {
		fmt.Fprintf(stderr, "nimblegate gateway tls-setup: write Caddyfile: %v\n", err)
		return 2
	}
	fmt.Fprintf(stdout, "  → wrote %s\n", *caddyfile)

	// Step 5 - flip the dashboard bind to localhost so it's no longer
	// directly reachable. The reverse proxy front door becomes the only
	// network surface.
	if !*noBindFlip {
		// Reuse the gatewayBindWith implementation directly - same testable
		// shape, same systemctl runner.
		bindRC := gatewayBindWith(
			[]string{"--unit", *unit, "localhost"},
			stdin, stdout, stderr, systemctl,
		)
		if bindRC != 0 {
			fmt.Fprintf(stderr, "nimblegate gateway tls-setup: gateway bind localhost returned %d\n", bindRC)
			return bindRC
		}
	}

	// Step 6 - reload + restart both services. Each step prints its own
	// status so the operator can see where any failure lands.
	for _, args := range [][]string{
		{"daemon-reload"},
		{"restart", "caddy"},
		{"restart", "nimblegate-dashboard"},
	} {
		if out, err := systemctl(args...); err != nil {
			fmt.Fprintf(stderr, "nimblegate gateway tls-setup: systemctl %s: %v\n%s\n",
				strings.Join(args, " "), err, out)
			return 2
		}
		fmt.Fprintf(stdout, "  → systemctl %s\n", strings.Join(args, " "))
	}

	fmt.Fprintf(stdout, "\nDone. Dashboard is now available at https://%s (Caddy is provisioning the cert on first hit if it hasn't already).\n", *domain)
	return 0
}

// domainPattern is a minimal-but-honest check: at least one dot, at least
// two labels of alphanumeric+dash (each starting + ending with alphanum),
// no trailing dot. Catches typos like "localhost" or "example" without
// trying to be a full RFC-compliant validator (that's Caddy's job at cert
// provisioning time, which has access to DNS + ACME challenge anyway).
var domainPattern = regexp.MustCompile(`^[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?)+$`)

func isPlausibleDomain(s string) bool {
	if len(s) == 0 || len(s) > 253 {
		return false
	}
	return domainPattern.MatchString(s)
}
