// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

package gitwrap

import (
	"fmt"
	"os"
	"path/filepath"
)

// ShimsDirName is the subdirectory under the user's home where nimblegate
// installs binary shims for git / apt / apt-get / rm. The shim directory
// is placed on PATH ahead of system paths so EVERY shell context - login
// shells, non-interactive shells (Claude Code's Bash tool, IDE shells, CI),
// even sh invocations - picks up the gates.
const ShimsDirName = ".appframes/shims"

// ShimsDir returns the absolute path to the shims directory. Uses HOME;
// falls back to ~ if HOME is unset (rare).
func ShimsDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home: %w", err)
	}
	return filepath.Join(home, ShimsDirName), nil
}

// shimSpec describes one shim file. Route is the literal argument list
// that appears between `nimblegate` and `"$@"` in the generated shim -
// i.e. the full subcommand-plus-name-args nimblegate expects.
//
// For `git`, nimblegate's subcommand takes git args directly, so Route =
// `"git"` and the generated line is `exec nimblegate git "$@"`.
//
// For `cmd`-based shims (apt, apt-get, rm), nimblegate's `cmd` subcommand
// takes the command name as its first arg, so Route = `"cmd apt"`,
// producing `exec nimblegate cmd apt "$@"`.
//
// CommitNoVerify is a special case for git: when set, the shim adds a
// `commit` arm that routes through nimblegate ONLY when `--no-verify` /
// `-n` is in the args. Regular `git commit` (no --no-verify) passes
// through so the pre-commit hook handles it. The point: prevent the
// silent skip-pre-commit-hook bypass that --no-verify enables.
type shimSpec struct {
	Name           string   // filename (and the bare command name)
	Route          string   // nimblegate subcommand args, e.g. "git" or "cmd rm"
	Verbs          []string // first-arg verbs that route through nimblegate
	RecursiveRm    bool     // special-cased rm: route only when a recursive flag is present
	CommitNoVerify bool     // git: also route `commit` if --no-verify / -n is present
}

// shimSpecs is the canonical list of commands nimblegate shims. Adding a
// new shim means adding an entry here; the install / uninstall paths
// handle the rest.
var shimSpecs = []shimSpec{
	{
		Name:           "git",
		Route:          "git",
		Verbs:          []string{"push", "reset", "branch", "clean", "rebase", "filter-branch", "filter-repo", "stash"},
		CommitNoVerify: true,
	},
	{
		Name:  "apt",
		Route: "cmd apt",
		Verbs: []string{"purge", "remove", "autoremove"},
	},
	{
		Name:  "apt-get",
		Route: "cmd apt-get",
		Verbs: []string{"purge", "remove", "autoremove"},
	},
	{
		Name:        "rm",
		Route:       "cmd rm",
		RecursiveRm: true,
	},
}

// renderShim returns the content of one shim shell script. The script:
//
//  1. Strips its own containing directory from PATH so subsequent
//     lookups (and any nimblegate-internal LookPath calls) resolve to the
//     real system binary instead of looping back into the shim.
//  2. Inspects the first argument (for verb-based shims) OR any argument
//     (for rm's recursive-flag shim).
//  3. exec's `nimblegate <subcommand> <name> ...` for destructive cases;
//     exec's the real binary directly for the common pass-through case.
//
// Performance: the common case (e.g. `git status`, `git log`, `rm
// file.txt`) goes straight to the real binary after a few lines of POSIX
// shell. The nimblegate binary is invoked only when the operation is
// actually destructive.
//
// Compatibility: POSIX sh syntax only (no bashisms). Works under
// /bin/sh, /bin/bash, /bin/zsh, dash, ash, busybox sh, etc.
func renderShim(spec shimSpec) string {
	header := `#!/bin/sh
# Generated by ` + "`nimblegate shell install --strict`" + `.
# Remove this file via ` + "`nimblegate shell uninstall --strict`" + ` or by
# editing $HOME/.appframes/shims/ directly.

# Strip our own shim dir from PATH so subsequent lookups find the real
# binary, not this shim. Without this step, exec'ing ` + spec.Name + ` below would
# recurse back into the shim forever.
SHIM_DIR="$(cd "$(dirname "$0")" && pwd)"
PATH=$(printf '%s' "$PATH" | tr ':' '\n' | grep -vxF "$SHIM_DIR" | tr '\n' ':' | sed 's/:$//')
export PATH

`
	if spec.RecursiveRm {
		return header + `# rm: route through nimblegate ONLY when a recursive flag is present, so
# common 'rm file.txt' invocations don't pay the nimblegate-invocation cost.
for arg in "$@"; do
    case "$arg" in
        -r|-R|--recursive|-rf|-Rf|-fr|-fR|-rfv|-vfr|-rfi|-irf|-rRf|-rfR)
            exec nimblegate ` + spec.Route + ` "$@"
            ;;
        -[A-Za-z]*[rR]*[A-Za-z]*)
            exec nimblegate ` + spec.Route + ` "$@"
            ;;
    esac
done
exec ` + spec.Name + ` "$@"
`
	}
	// Verb-based shim.
	caseLine := ""
	for i, v := range spec.Verbs {
		if i > 0 {
			caseLine += "|"
		}
		caseLine += v
	}
	commitArm := ""
	if spec.CommitNoVerify {
		commitArm = `    commit)
        # Intercept --no-verify (or -n) - that flag silently skips the
        # pre-commit hook, which is one of nimblegate's load-bearing gates.
        # Regular ` + "`git commit`" + ` (without --no-verify) passes through so the
        # pre-commit hook fires normally.
        for arg in "$@"; do
            case "$arg" in
                --no-verify|-n)
                    exec nimblegate ` + spec.Route + ` "$@"
                    ;;
            esac
        done
        exec ` + spec.Name + ` "$@"
        ;;
`
	}
	return header + `case "$1" in
    ` + caseLine + `)
        exec nimblegate ` + spec.Route + ` "$@"
        ;;
` + commitArm + `    *)
        exec ` + spec.Name + ` "$@"
        ;;
esac
`
}

// InstallShims writes the shim scripts to ~/.appframes/shims/. Idempotent:
// re-running overwrites existing shims with current content. Returns the
// shims directory path (so the caller can emit a setup instruction
// referencing it) and any error.
func InstallShims() (string, error) {
	dir, err := ShimsDir()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return dir, fmt.Errorf("mkdir %s: %w", dir, err)
	}
	for _, spec := range shimSpecs {
		path := filepath.Join(dir, spec.Name)
		content := renderShim(spec)
		if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
			return dir, fmt.Errorf("write %s: %w", path, err)
		}
	}
	return dir, nil
}

// UninstallShims removes every shim file nimblegate installed under
// ~/.appframes/shims/. Leaves the directory in place if other files are
// present (e.g. user-added shims); removes it only if empty after
// removing our shims.
func UninstallShims() (string, error) {
	dir, err := ShimsDir()
	if err != nil {
		return "", err
	}
	if _, err := os.Stat(dir); err != nil {
		return dir, nil // nothing to do
	}
	for _, spec := range shimSpecs {
		path := filepath.Join(dir, spec.Name)
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return dir, fmt.Errorf("remove %s: %w", path, err)
		}
	}
	// Best-effort rmdir: only succeeds if dir is empty.
	_ = os.Remove(dir)
	return dir, nil
}

// RenderShimForName returns the shell-script content of the shim with
// the given name, or "" if no shim exists with that name. Used by
// `nimblegate shell print --strict` to display what would be written
// without actually writing.
func RenderShimForName(name string) string {
	for _, s := range shimSpecs {
		if s.Name == name {
			return renderShim(s)
		}
	}
	return ""
}

// ShimNames returns the filenames of the shims nimblegate installs. Used
// by tests + by `nimblegate shell print --strict` for inspection.
func ShimNames() []string {
	out := make([]string, len(shimSpecs))
	for i, s := range shimSpecs {
		out[i] = s.Name
	}
	return out
}
